In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib plotly
!pip install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
ERROR: Could not find a version that satisfies the requirement poltly (from versions: none)
ERROR: No matching distribution found for poltly
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [7]:
# para colocar a biblioteca em uso, devemos importar ela
import pandas as pd

In [9]:
# criar o esqueleto do arquivo
# usaremos dicionarios para criar os dados
# dicionário funciona com a ideia de chave-valor ou chave-valores

In [12]:
dados = {
    'nome': ['André', 'Paulo', 'Aline', 'Paola'],
    'idade': [36,25,30,18],
    'cidade': ['Sorocaba','Indaiatuba','São Paulo','Registro']
}

# A biblioteca PANDAS pode transformar uma biblioteca em uma "tabela"
# Esse pedaço é chamado de DataFrame
#Ex.:
df_dados = pd.DataFrame(dados)

display(df_dados)

    nome  idade      cidade
0  André     36    Sorocaba
1  Paulo     25  Indaiatuba
2  Aline     30   São Paulo
3  Paola     18    Registro

In [14]:
# criar arquivo csv

# para criar, precisamos de dados
#chamamos os dados e atribuimos a função "to_"

df_dados.to_csv("teste_pandas.csv", index=False)

In [15]:
# como ler um arquivo que me enviaram
# criar variavel e aplicar o comando read

# df_ler_dados = pd.read_csv('caminho_do_arquivo')
df_ler_dados = pd.read_csv('/content/teste_pandas.csv')

In [16]:
# vamos popular a tabela

novos_dados = {
    'nome':['Flavia','Cláudio','Fernanda'],
    'idade':[50,63,32],
    'cidade':['Sorocaba','Iguape','Curitiba']
}
df_novos_dados = pd.DataFrame(novos_dados)
# Criar variavel para receber os dados, chama a PANDAS com a função DataFrame
#juntar = concatenar o antigo com o novo
df_dados_juntos = pd.concat([df_ler_dados,df_novos_dados], ignore_index=True)

#voltar para o CSV
df_dados_juntos.to_csv('teste_dados.csv',index=False)
display(df_dados_juntos)

       nome  idade      cidade
0     André     36    Sorocaba
1     Paulo     25  Indaiatuba
2     Aline     30   São Paulo
3     Paola     18    Registro
4    Flavia     50    Sorocaba
5   Cláudio     63      Iguape
6  Fernanda     32    Curitiba